"""Register-address naming for capture analysis.

Two tiers, deliberately separated:

* The registers in :mod:`novasun.registers` -- corroborated, and part of this
  repository.
* An optional index imported from an external address map, kept **outside** the
  repository. The largest such map is the ``AddressMapping`` enum in
  ``sarakusha/novastar``'s ``@novastar/native``, which was generated by
  decompiling NovaLCT's assemblies. Around 1,500 names, and enormously useful
  for reading a capture -- an unnamed address is a research task, a named one is
  usually a five-second look.

The split is the point. Using those names to *read your own captures* keeps them
as facts you verify against hardware; vendoring the generated file into a
product is a different position, and it is not one this repository takes for
you. Import it locally with ``novasun names import``, and it lands in your home
directory, not in the source tree.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from . import registers as reg

DEFAULT_INDEX_PATH = Path.home() / ".novasun" / "addressmap.json"

_ENUM_ENTRY = re.compile(
    r"^\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?P<value>0x[0-9A-Fa-f_]+|\d+)\s*,"
)


def _builtin_names() -> dict[int, str]:
    """Names for the registers this repository documents itself."""
    skip = {"CONFIDENCE", "NORMAL", "ENGAGED"}
    names: dict[int, str] = {}
    for attribute in dir(reg):
        if attribute.startswith("_") or attribute in skip or not attribute.isupper():
            continue
        value = getattr(reg, attribute)
        if isinstance(value, int) and not isinstance(value, bool):
            # Several constants share an address (RGB_BRIGHTNESS and
            # RED_BRIGHTNESS, for instance); keep them all, joined.
            existing = names.get(value)
            names[value] = f"{existing} / {attribute}" if existing else attribute
    return names


@dataclass
class NameIndex:
    """Address -> human name, built-in entries taking precedence."""

    builtin: dict[int, str] = field(default_factory=_builtin_names)
    imported: dict[int, str] = field(default_factory=dict)

    def lookup(self, address: int) -> str | None:
        if address in self.builtin:
            return self.builtin[address]
        if address in self.imported:
            return self.imported[address]
        # Block registers are read and written in pieces, and chunked transfers
        # add the offset to the address. Attribute those to the block rather
        # than reporting them as unknown -- but only for registers whose length
        # is actually known, so this never guesses.
        for base, size in reg.BLOCKS.items():
            if 0 < address - base < size:
                return f"{self.builtin.get(base, hex(base))}+0x{address - base:x}"
        return None

    @property
    def size(self) -> int:
        return len(set(self.builtin) | set(self.imported))

    def save(self, path: Path = DEFAULT_INDEX_PATH) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps({str(k): v for k, v in sorted(self.imported.items())}, indent=1)
        )
        return path

    @classmethod
    def load(cls, path: Path = DEFAULT_INDEX_PATH) -> "NameIndex":
        index = cls()
        if path.exists():
            raw = json.loads(path.read_text())
            index.imported = {int(k): v for k, v in raw.items()}
        return index


def parse_address_mapping(source: str) -> dict[int, str]:
    """Extract ``Name = value`` pairs from a TypeScript enum body.

    Written for ``@novastar/native``'s ``AddressMapping.ts``, but it will read
    any enum of that shape. ``*Occupancy`` entries are sizes rather than
    addresses and are skipped.
    """
    names: dict[int, str] = {}
    for line in source.splitlines():
        match = _ENUM_ENTRY.match(line)
        if not match:
            continue
        name = match.group("name")
        if name.endswith("Occupancy"):
            continue
        value = match.group("value")
        address = int(value.replace("_", ""), 0)
        existing = names.get(address)
        names[address] = f"{existing} / {name}" if existing else name
    return names


def import_address_mapping(source_path: Path, index_path: Path = DEFAULT_INDEX_PATH) -> NameIndex:
    """Read an external address map and cache it outside the source tree."""
    index = NameIndex.load(index_path)
    index.imported.update(parse_address_mapping(Path(source_path).read_text()))
    index.save(index_path)
    return index


_default: NameIndex | None = None


def default_index() -> NameIndex:
    """Process-wide index: built-ins plus whatever has been imported locally."""
    global _default
    if _default is None:
        _default = NameIndex.load()
    return _default
